spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_student_db
    username: postgres  # your database username
    password: 123@ace      # your db password
  flyway:
    user: postgres
    password: 123@ace
    url: jdbc:postgresql://localhost:5432/reactive_student_db